"""Image repository — raw SQL CRUD over the ``generated_images`` table.

Uses ``asyncpg`` directly (no ORM).
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime

import asyncpg
import structlog

from app.models.image import GeneratedImage

logger = structlog.get_logger(__name__)


class ImageRepository:
    """Data-access layer for the ``generated_images`` table.

    Args:
        pool: An active ``asyncpg.Pool`` instance.
    """

    def __init__(self, pool: asyncpg.Pool) -> None:
        self._pool = pool

    async def create(
        self,
        thread_id: uuid.UUID,
        user_id: str,
        prompt: str,
        s3_key: str,
        s3_url: str,
        model: str,
        request_message_id: str | None = None,
    ) -> GeneratedImage:
        """Insert a generated image record.

        Args:
            thread_id: Parent thread UUID.
            user_id: Saleor user ID for quota tracking.
            prompt: The prompt used to generate the image.
            s3_key: S3 object key (path within the bucket).
            s3_url: Public S3 URL of the image.
            model: Model identifier (e.g. ``"dall-e-3"``).
            request_message_id: ``HumanMessage.id`` that triggered
                generation; links the image to its turn in thread history
                (FR-020, FR-051).  ``None`` if unavailable.

        Returns:
            The newly created ``GeneratedImage``.
        """
        image_id = uuid.uuid4()
        async with self._pool.acquire() as conn:
            row = await conn.fetchrow(
                """
                INSERT INTO generated_images
                    (id, thread_id, user_id, prompt, s3_key, s3_url, model, request_message_id)
                VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
                RETURNING id, thread_id, user_id, prompt, s3_key, s3_url, model,
                          request_message_id, created_at
                """,
                image_id,
                thread_id,
                user_id,
                prompt,
                s3_key,
                s3_url,
                model,
                request_message_id,
            )
        image = GeneratedImage(**dict(row))
        logger.info(
            "Image record created",
            image_id=str(image.id),
            thread_id=str(thread_id),
        )
        return image

    async def count_today(self, user_id: str) -> int:
        """Count images generated by a user today (UTC calendar day).

        Used for daily quota enforcement before dispatching a Celery task.

        Args:
            user_id: Saleor user ID.

        Returns:
            Number of images generated since midnight UTC today.
        """
        today = datetime.now(tz=UTC).date()
        async with self._pool.acquire() as conn:
            count: int = await conn.fetchval(
                """
                SELECT COUNT(*)
                FROM generated_images
                WHERE user_id = $1
                  AND created_at >= $2::timestamptz
                """,
                user_id,
                today,
            )
        return count

    async def list_by_thread(self, thread_id: uuid.UUID) -> list[GeneratedImage]:
        """Return all images for a thread, newest first.

        Args:
            thread_id: UUID of the parent thread.

        Returns:
            List of ``GeneratedImage`` domain models.
        """
        async with self._pool.acquire() as conn:
            rows = await conn.fetch(
                """
                SELECT id, thread_id, user_id, prompt, s3_key, s3_url, model,
                       request_message_id, created_at
                FROM generated_images
                WHERE thread_id = $1
                ORDER BY created_at DESC
                """,
                thread_id,
            )
        return [GeneratedImage(**dict(row)) for row in rows]
